
package com.cw.demo.drools;

import com.cw.demo.drools.PointDomain

dialect  "mvel"
//退货减10分
rule "subBackNumsPoint"
    salience 10
    lock-on-active true
    when
        $pointDomain:PointDomain(backNums>=1)

    then
        $pointDomain.setPoint($pointDomain.getPoint()-10);
        $pointDomain.recordPointLog($pointDomain.getUserName(),"subBackNumPoint");
end

rule "subBackMoneyPoint"
    salience 9
    lock-on-active true
    when
        $pointDomain:PointDomain(backMoney>=100)

    then
        $pointDomain.setPoint($pointDomain.getPoint()-10);
        $pointDomain.recordPointLog($pointDomain.getUserName(),"subBackMoneyPoint");
end
